services:
  mysql:
    image: mysql:8.0
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql
    ports:
      - "0.0.0.0:3307:3306"

    restart: always